src/main/java/ues/occ/edu/sv/ingenieria/prn335/cinewebapp/entity/Pago.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ues.occ.edu.sv.ingenieria.prn335.cinewebapp.entity;

import java.io.Serializable;
import java.util.List;
import javax.json.bind.annotation.JsonbTransient;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author melvin
 */
@Entity
@Table(name = "pago", catalog = "cine", schema = "")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Pago.findAll", query = "SELECT p FROM Pago p"),
    @NamedQuery(name = "Pago.findByIdPago", query = "SELECT p FROM Pago p WHERE p.idPago = :idPago"),
    @NamedQuery(name = "Pago.findByMonto", query = "SELECT p FROM Pago p WHERE p.monto = :monto")})
public class Pago implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id_pago", nullable = false)
    private Integer idPago;
    @Basic(optional = false)
    @NotNull
    @Column(name = "monto", nullable = false)
    private double monto;
    @ManyToMany(mappedBy = "pagoList")
    private List<Factura> facturaList;
    @JoinColumn(name = "id_tipo_pago", referencedColumnName = "id_tipo_pago", nullable = false)
    @ManyToOne(optional = false)
    private TipoPago idTipoPago;

    public Pago() {
    }

    public Pago(Integer idPago) {
        this.idPago = idPago;
    }

    public Pago(Integer idPago, double monto) {
        this.idPago = idPago;
        this.monto = monto;
    }

    public Integer getIdPago() {
        return idPago;
    }

    public void setIdPago(Integer idPago) {
        this.idPago = idPago;
    }

    public double getMonto() {
        return monto;
    }

    public void setMonto(double monto) {
        this.monto = monto;
    }

    @JsonbTransient
    @XmlTransient
    public List<Factura> getFacturaList() {
        return facturaList;
    }

    public void setFacturaList(List<Factura> facturaList) {
        this.facturaList = facturaList;
    }

    public TipoPago getIdTipoPago() {
        return idTipoPago;
    }

    public void setIdTipoPago(TipoPago idTipoPago) {
        this.idTipoPago = idTipoPago;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (idPago != null ? idPago.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Pago)) {
            return false;
        }
        Pago other = (Pago) object;
        if ((this.idPago == null && other.idPago != null) || (this.idPago != null && !this.idPago.equals(other.idPago))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "ues.occ.edu.sv.ingenieria.prn335.cinewebapp.entity.Pago[ idPago=" + idPago + " ]";
    }
    
}

src/main/java/ues/occ/edu/sv/ingenieria/prn335/cinewebapp/boundary/PagosBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ues.occ.edu.sv.ingenieria.prn335.cinewebapp.boundary;

import java.io.Serializable;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import javax.ws.rs.client.Client;
import javax.ws.rs.client.ClientBuilder;
import javax.ws.rs.client.WebTarget;
import javax.ws.rs.core.GenericType;
import javax.ws.rs.core.Response;
import ues.occ.edu.sv.ingenieria.prn335.cinewebapp.entity.TipoPago;

/**
 *
 * @author vladimir
 */
@Named(value = "pagosBean")
@ViewScoped
public class PagosBean implements Serializable{
    
    WebTarget webtarget;
    Client cliente;
    List<TipoPago> tipoPagosList;
    TipoPago SelectTipo;
    public PagosBean() {
    this.cliente = ClientBuilder.newClient();
    this.webtarget=cliente.target("http://localhost:8080/parcial3progra");
    }
    
    @PostConstruct
    public void iniciar(){
        Response respuesta =this.webtarget.path("/servicios/boundary/pago/tipopagos").request().get();
        tipoPagosList=respuesta.readEntity(new GenericType<List<TipoPago>>(){
        });
    }

    public TipoPago getSelectTipo() {
        return SelectTipo;
    }

    public void setSelectTipo(TipoPago SelectTipo) {
        this.SelectTipo = SelectTipo;
    }

    public List<TipoPago> getTipoPagosList() {
        return tipoPagosList;
    }

    public void setTipoPagosList(List<TipoPago> tipoPagosList) {
        this.tipoPagosList = tipoPagosList;
    }
    
    
}

src/main/webapp/paginas/Pago.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets" 
                template="/resources/template/pagesTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://xmlns.jcp.org/jsf/core">
    <ui:define name="title">Pagos</ui:define>
    <ui:define name="content">
        <h:form id="reserva">
            <p:panelGrid id="panelgridReserva" columns="2">
                <p:outputLabel value="Reserva"/>
                <p:inputNumber value="" decimalPlaces="0" />
            </p:panelGrid>
        </h:form>
        <h:form id="boletos">
            <p:repeat value="" var="car">
                <h:panelGrid columns="1" style="width:100%" columnClasses="logo,detail">

                    <p:outputPanel>
                        <h:panelGrid columns="2" cellpadding="5">
                            <h:outputText value="Id Boleto:" />
                            <h:outputText value="45464" style="font-weight: bold"/>

                            <h:outputText value="Pelicula" />
                            <h:outputText value="Frozen" style="font-weight: bold"/>

                            <h:outputText value="Fila" />
                            <h:outputText value="1" style="font-weight: bold"/>
                            
                            <h:outputText value="Columna" />
                            <h:outputText value="1" style="font-weight: bold"/>
                        </h:panelGrid>
                    </p:outputPanel>
                </h:panelGrid>
                <hr />
            </p:repeat>
        </h:form>
        
        <h:form>     
            <p:growl id="message" showDetail="true" />
            <p:commandButton value="Confirmar boletos" action="#{dialogView.destroyWorld}" update="message">
                <p:confirm header="Confirmacion de boletos" message="Esta seguro?" icon="pi pi-exclamation-triangle" />
            </p:commandButton>

            <p:confirmDialog global="true" showEffect="fade" hideEffect="fade">
                <p:commandButton value="Si" type="button" styleClass="ui-confirmdialog-yes" icon="pi pi-check" />
                <p:commandButton value="No" type="button" styleClass="ui-confirmdialog-no" icon="pi pi-times" />
            </p:confirmDialog>      
        </h:form>

        <h:form id="pagos">
            <p:dataGrid value="#{sucursalBean.peliculaList}" var="pl" columns="3" layout="grid"
                            rows="12" paginator="true" paginatorPosition="bottom" style="width: 500px;align-self: center" id="cars"
                            paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                            rowsPerPageTemplate="6,12,16" >

                    <f:facet name="header">
                       <p:panelGrid id="panelgridTipo" columns="3">
                <p:outputLabel value="Tipo de Pago: "/>
                <p:selectOneMenu id="TipoPago" value="#{pagosBean.selectTipo}" converter="entidadConverter">
                    <f:selectItem itemLabel="Seleccione tipo pago" itemValue="#{null}"/>
                    <f:selectItems value="#{pagosBean.tipoPagosList}" var="tp" itemValue="#{tp}" itemLabel="#{tp.tipoPago}"/>
                </p:selectOneMenu>
                       </p:panelGrid>
             Formas de pago
                    </f:facet>

                </p:dataGrid>
        </h:form>
        
        <h:form>     
            <p:growl id="message" showDetail="true" />
            <p:commandButton value="Confirmar pago" action="#{dialogView.destroyWorld}" update="message">
                <p:confirm header="Confirmacion de pago" message="Esta seguro?" icon="pi pi-exclamation-triangle" />
            </p:commandButton>

            <p:confirmDialog global="true" showEffect="fade" hideEffect="fade">
                <p:commandButton value="Si" type="button" styleClass="ui-confirmdialog-yes" icon="pi pi-check" />
                <p:commandButton value="No" type="button" styleClass="ui-confirmdialog-no" icon="pi pi-times" />
            </p:confirmDialog>      
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/paginas/Reserva.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets" 
                template="/resources/template/pagesTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://xmlns.jcp.org/jsf/core">
    <ui:define name="title">Reservas</ui:define>
    <ui:define name="content">
        <h:form id="sucursales">
            <p:panelGrid id="panelgridSucursal" columns="3" styleClass="companyHeaderGrid">
                <p:outputLabel value="Sucursal: "/>
                <p:selectOneMenu id="Sucursales" value="#{sucursalBean.selectedSucursal}" converter="entidadConverter">
                    <f:selectItem itemLabel="Seleccione una sucursal" itemValue="#{null}"/>
                    <f:selectItems value="#{sucursalBean.sucursales}" var="sl" itemValue="#{sl}" itemLabel="#{sl.nombre}"/>
                </p:selectOneMenu>
                <p:commandButton value="Aceptar" actionListener="#{sucursalBean.onSucursalSelect}" update=":funciones"/>
            </p:panelGrid>
        </h:form>

        <h:form id="funciones">
            <center>
                <p:dataGrid value="#{sucursalBean.peliculaList}" var="pl" columns="3" layout="grid"
                            rows="12" paginator="true" paginatorPosition="bottom" style="width: 1300px;align-self: center" id="cars"
                            paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                            rowsPerPageTemplate="6,12,16" rendered="#{sucursalBean.selectedSucursal!=null}">

                    <f:facet name="header">
                        Peliculas
                    </f:facet>

                    <p:panel header="#{pl.titulo}" style="text-align:center">
                        <center>
                            <p:panelGrid columns="2">
                                <p:outputLabel value="Director: "/>
                                <h:outputText value="#{pl.idDirector.nombre} #{pl.idDirector.apellido}"/>
                                <p:outputLabel value="Clasificacion: "/>
                                <h:outputText value="#{pl.idClasificacion.clasificacion}"/>
                                <p:outputLabel value="Duracion: "/>
                                <h:outputText value="#{pl.duracion}"/>
                            </p:panelGrid>
                            <br></br>
                            <p:commandLink update=" :funciones" oncomplete="PF('funDialog').show()" title="View Detail" actionListener="#{sucursalBean.onPeliculaSelect(pl.idPelicula)}">
                                <h:outputText value="Funciones" style="margin:0 auto;"/>
                            </p:commandLink>
                        </center>
                    </p:panel>
                </p:dataGrid>
                
                <p:dialog header="Funciones" widgetVar="funDialog" modal="true" showEffect="fade" hideEffect="fade" resizable="false" width="300px">
                            <p:outputPanel id="carDetail" style="text-align:center;">
                                
                                <p:dataTable value="#{sucursalBean.funcionList}" var="f">
                                    <p:column headerText="HORA">#{f.fecha}</p:column>
                                </p:dataTable>
                            </p:outputPanel>
                        </p:dialog>
            </center>
        </h:form>
        
        <p:panelGrid id="asiento" rendered="#{sucursalBean.selectedSucursal!=null}">
            <table cellpadding="5">
                        <thead>
                            <tr>
                                <th>Filas</th>
                                <th align="center" colspan="100">Asientos</th>
                            </tr>
                        </thead>
                        <tbody>
                            <ui:repeat value="#{reservaFrmBean.asientos}" var="fi" varStatus="filas">
                                <tr>
                                    <td>No.#{fi.row}</td>
                                    <ui:repeat value="#{fi.cols}" var="c">
                                        <td>
                                            <p:commandButton value="#{c.idAsiento}" disabled="#{c.estado==false}" rendered="#{c.selected==false}" action="#{reservaFrmBean.selecionarDeseleccionarAsiento(fi.row, c.col)}" update="asiento"/>
                                            <p:commandButton value="#{c.idAsiento}" disabled="#{c.estado==false}" rendered="#{c.selected==true}" class="ui-button-selected" action="#{reservaFrmBean.selecionarDeseleccionarAsiento(fi.row, c.col)}" update="asiento"/>
                                        </td>
                                    </ui:repeat>
                                </tr>
                            </ui:repeat>
                        </tbody>
                    </table>
        </p:panelGrid>


    </ui:define>
</ui:composition>